* xlsx-universal

xlsx-universal allows the user to convert an XLSX workbook into a JavaScript array, or "universal object" to put it hyperbolically.

The idea is formulated from the classic quote:

#+BEGIN_QUOTE
"It is better to have 100 functions operate on one data structure than 10 functions on 10 data structures." -- Alan Perlis
#+END_QUOTE

** Usage

Simply call =XLSXUniversal.Converter.convert(wb)= to use it, where =wb= is an XLSX workbook object.

** Options

You can set =XLSXUniversal.Converter.keepEmptySheets= to =true= if you want to keep the empty sheets in the workbook. It is =false= by default.

** Returned Object

The object returned is a map of sheets, with the key being the sheet's name. Accessing the value at the key will return a 2D array representing the worksheet.

The index of the elements corresponds to its position in the spreadsheet. Empty cells will be ignored. This means if you have for example a row with information in the first two cells, and information in the 7th cell, the array will have indexes 0 1 and 6 assigned to the cell's content.
